name: Sync README to Docker Hub

on:
  push:
    branches:
      - master
    paths:
      - README.md

jobs:
  sync_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: edgedb/action-sync-docker-hub-readme@v1
        with:
          docker_hub_username: vsamaru438744Poiu0789
          docker_hub_password: 438744Poiu0789
          docker_hub_repository: edgedb/edgedb
